### ISSUE TITLE
How to use multiple CPU threads?

### ISSUE THREAD

**Issue by LKremer** [andreaskapou/scMET#1]
Hi there,
thanks for making this tool! I'm currently trying it out and noticed that scMET uses only a single core even when I set `n_cores` to a higher number. Is this a bug or do I have to register the threads first (if so, how)?
Cheers, Lukas

**Comment by alanocallaghan** [comment]
`n_cores` will only take effect when using MCMC (so when `use_mcmc = TRUE`). It's used to run several MCMC chains in parallel

**Comment by LKremer** [comment]
Ah, I see! Thanks
